services:

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8001:8000"

    entrypoint: "./entrypoint_web.sh"
#    environment: &be_environment
#      POSTGRES_HOST: postgres
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_HOST_AUTH_METHOD: trust
#      POSTGRES_PORT: 5432
