# Generated by Django 2.1.1 on 2018-09-28 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(5, 'Resume'), (3, 'Project'), (1, 'Quote'), (7, 'Type3'), (9, 'Type5'), (10, 'Type6'), (0, 'Blog post'), (8, 'Type4'), (6, 'Address'), (2, 'Service'), (4, 'About')], default=0)),
                ('title', models.CharField(max_length=256)),
                ('image', models.URLField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(6, 'Type2'), (3, 'Quote'), (2, 'Email'), (9, 'Type5'), (10, 'Type6'), (0, 'Name'), (4, 'Address'), (5, 'Type1'), (8, 'Type4'), (1, 'Tagline'), (7, 'Type3')], default=0)),
                ('text', models.CharField(max_length=512)),
            ],
        ),
    ]
