# Generated by Django 2.1.1 on 2018-09-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='para_images/'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(9, 'Type5'), (1, 'Quote'), (10, 'Type6'), (0, 'Blog post'), (2, 'Service'), (5, 'Resume'), (6, 'Address'), (7, 'Type3'), (4, 'About'), (8, 'Type4'), (3, 'Project')], default=0),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Type1'), (2, 'Email'), (3, 'Quote'), (6, 'Type2'), (0, 'Name'), (10, 'Type6'), (7, 'Type3'), (4, 'Address'), (1, 'Tagline'), (8, 'Type4'), (9, 'Type5')], default=0),
        ),
    ]
