# Generated by Django 2.2 on 2019-09-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190924_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(7, 'Type3'), (0, 'Blog post'), (4, 'About'), (8, 'Type4'), (9, 'Type5'), (6, 'Address'), (5, 'Resume'), (2, 'Service'), (10, 'Type6'), (3, 'Project'), (1, 'Quote')], default=0),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tagline'), (7, 'Type3'), (10, 'Type6'), (8, 'Type4'), (9, 'Type5'), (2, 'Email'), (4, 'Address'), (0, 'Name'), (6, 'Type2'), (5, 'Type1'), (3, 'Quote')], default=0),
        ),
    ]
