# Generated by Django 2.2 on 2019-10-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190924_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Type6'), (2, 'Service'), (3, 'Project'), (9, 'Type5'), (5, 'Short-Bio'), (0, 'Normal'), (7, 'Type3'), (4, 'About'), (1, 'Quote'), (8, 'Type4'), (6, 'Address')], default=0),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(7, 'Type3'), (9, 'Type5'), (2, 'Email'), (10, 'Type6'), (0, 'Name'), (8, 'Type4'), (6, 'Type2'), (1, 'Tagline'), (3, 'Quote'), (4, 'Address'), (5, 'Type1')], default=0),
        ),
    ]
