# Generated by Django 2.2 on 2021-02-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20191005_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Normal'), (1, 'Quote'), (2, 'Service'), (3, 'Project'), (4, 'About'), (5, 'Short-Bio'), (6, 'Address'), (7, 'Type3'), (8, 'Type4'), (9, 'Type5'), (10, 'Type6')], default=0),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Name'), (1, 'Tagline'), (2, 'Email'), (3, 'Quote'), (4, 'Address'), (5, 'Type1'), (6, 'Type2'), (7, 'Type3'), (8, 'Type4'), (9, 'Type5'), (10, 'Type6')], default=0),
        ),
    ]
