# Generated by Django 2.2 on 2019-09-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190924_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='side_para_bottom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='side_para_middle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='side_para_top',
            field=models.TextField(blank=True, null=True),
        ),
    ]
