# Generated by Django 2.2 on 2019-09-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20190924_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhistory',
            name='side_para_middle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workhistory',
            name='side_para_top',
            field=models.TextField(blank=True, null=True),
        ),
    ]
