# Generated by Django 2.2 on 2019-10-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20190924_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='image',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='service',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='para_images/'),
        ),
    ]
