# Generated by Django 2.2 on 2019-10-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20191005_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhistory',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='para_images/'),
        ),
    ]
