# Generated by Django 2.2 on 2019-10-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_workhistory_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workhistory',
            old_name='image',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='service',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workhistory',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
