# Generated by Django 2.2 on 2021-02-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20191005_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='serial',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workhistory',
            name='serial',
            field=models.SmallIntegerField(default=0),
        ),
    ]
